### ISSUE TITLE
What is equivalent to this plugin, but for plain `cf push`?

### ISSUE THREAD

**Issue by drnic** [cappyzawa/cf-push-with-vault#2]
Perhaps could the README explain how to do the same thing but without the bespoke plugin? I'm interested because I think many people are using `cf v3-push` or https://github.com/concourse/cf-resource or a zero-downtime deployment plugin, and might not be able to switch to a different plugin for deployment.

**Comment by cappyzawa** [comment]
I implement this for users who don't use them.

If cf server version in the company is old, modern command(`cf v3-push`) and option(`-var`) are unavailable.

And I use https://github.com/concourse/cf-resource but I use this plugin when pushing cf app from local.
It is convenient to easily refer to the same vault credential as cf resource. 

Thanks!

**Comment by cappyzawa** [comment]
I added description.

https://github.com/cappyzawa/cf-push-with-vault/commit/3b021255ffbd61652c89e0c750715f4678f18c10

**Comment by drnic** [comment]
Thanks!
